name: Devdocs.ru
description: "Блог про Битрикс, Yii2, Laravel и все что связано с вебразработкой"

aboutPage: false

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate, jekyll-seo-tag]
paginate: 20
baseurl: /
domain_name: 'http://devdocs.ru'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'devdocs'

tags: [bitrix,yii2,Laravel]

# Details for the RSS feed generator
url:            'http://devdocs.ru'
author:         'Maxyc Webber'
authorTwitter:  'maxyc'
social:
    name: 'Maxyc Webber'
    links:
        - https://twitter.com/maxyc
        - https://www.facebook.com/maxyc.Webber
        - https://www.linkedin.com/in/maxyc.webber
        - https://vk.com/maxyc
        - https://github.com/maxyc

permalink:       :year/:month/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post